export enum EQueryKeys {
  GET_DEPARTMENTS = 'GET_DEPARTMENTS',

  GET_POSTS = 'GET_POSTS',

  GET_EMPLOYEE = 'GET_EMPLOYEE',
  GET_EMPLOYEE_VISIT_HISTORY = 'GET_EMPLOYEE_VISIT_HISTORY',

  GET_EVENT = 'GET_EVENT',
}
